### ISSUE TITLE
Laporan Bugs

### ISSUE THREAD

**Issue by rizukurizu** [mhazm/Saino-sama#15]
1. error terjadi jika mute, user tidak dikenakan denda dan nilai hanya NaN
2. error ketika afk, jika sedang afk, dan chat di server berbeda maka status afk tersebut akan hilang
3. error ketika mute, user tidak terambil semua rolenya dan tidak diberikan role mute
4. error ketika mute, Nilai mute pada profile tidak bertambah

![Cuplikan layar 2021-06-09 083128](https://user-images.githubusercontent.com/79633934/121278625-37009c00-c8fd-11eb-8556-90d561cc0839.png)

**Comment by mhazm** [comment]
Sip gan.. nanti saya proses :)

**Comment by rizukurizu** [comment]
siapp kang, terimakasih banyak ya :D
