### ISSUE TITLE
request perubahan/penambahan future pada bot

### ISSUE THREAD

**Issue by rizukurizu** [mhazm/Saino-sama#17]
**Is your feature request related to a problem? Please describe.**
NH REQUEST & permintaan beberapa perubahan

1. buat agar ketika warn, mute dan afk (?) user tertag, bukan hanya menampilkan nama saja

2, buat agar bisa multi search/tags karna kalo semisalnya cmd ( k.nh-tag anal tanlines) karena itu yg kebaca biasanya cuma huruf/kata depan bisa juga yg belakang, jadi hanya (k.nh-tag tanlines) saja yg terbaca

3. sementara ketika cmd (k.nh-search armpit licking) yg seharusnya nyambung yg kebaca malah hanya (armpit / lickingnya) saja 

4. buat agar bisa search untuk semua bahasa dengan tambahan cmd di depannya

5. buat agar bisa search artis

6. hilangkan gambar icon / emoji pada saat cari manga yang ada di kiri

7. buat agar ketika afk, bot dapat memunculkan stiker, bukan hanya nama dari stiker saja

**Describe the solution you'd like**
req 1, kenapa dibuat agar bisa tertag? agar lebih oke aja penampilannya

req 2. agar user leluasa mencari berbagai genre yg digabungkan
untuk req 2 dan 3 problemnya sama yg kebaca hanya bagian depan/belakang saja ketika mencari suatu judul / tags

req 4. untuk memudahkan user dengan menambahkan bahasa yang ada pada dojin dan buat agar default bahasanya ketika search yg muncul adalah bahasa inggris

req 5. agar memudahkan ketika mencari artis dengan kerword, kurang lebih sama seperti cmd untuk mencari anime, dan di tampilkan judul/artist yg tersedia

req 6, agar lebih clean? karna icon arrow ke atas aja yg di kanan sudah lebih dari cukup

req 7, agar ketika afk lebih oke tampilannya

**Describe alternatives you've considered**
silahkan di pertimbangkan gimana enaknya karna akang tau juga gmn enaknya

**Additional context**
gak ada ss karna ini pure request dari saya

**Comment by mhazm** [comment]
Pertanyaan saya
1. Untuk warn dan mute itu membernya akan mendapatkan DM dari bot bahwa mereka terkena warn/mute dan kalau untuk AFK untuk apa membuat notif? Karena kalau kita ambil kegunaan dari afk sendiri hanya untuk menunjukan bahwa user tersebut sedang away jadi ngga terlalu perlukan untuk mention?
2. Keterbatasan dari api-nya memang begitu.. join tag genre itu nggabisa
3. Sama kaya nomer 2 tapi saya nanti bakal coba untuk bisa multiple search.. entah gimana dah
4. Search by bahasa itu udh bisa commandnya k.nh-tag / k.nh-search <query> <bahasa> pilihannya adalah defaultnya eng, kalau mau japanese isi jp atau china ch
5. Cari per scanlation?? soalnya cuma ada scanlation ngga ada data artis.
6. Oke..
7. Bot nggabisa menampilkan sticker karena message bot diatur agar user tidak bisa mention orang, ini untuk meminimalkan kejadian member afk tapi dengan mention member lain atau role jadi dibuatlah sistem not mentionable dan jadi berefek pada icon dll.

Sementara saya akan fix icon 6 tapi ini akan saya masukan kedalam branch jadi akan dipublish setelah semua issue ini kelar.

**Comment by rizukurizu** [comment]
ah ternyata maksud yang saya pinta no 1 berhubungan dengan no 7, jadi itu cara yg bagus untuk meminimalisir kejadian orang sengaja afk dengan mention orang lain

untuk no 2 dan 3 mohon bantuannya ya kang

untuk nomor 4 mohon infonya untuk cmd berdasarkan bahasa dan lainnya, karna saya bingung untuk search berdasarkan artist

untuk no 5 di nh menyediakan tags list artist, apakah bisa terhubung? nhentai.net/artists/
jadi bukan berdasarkan scanlation

![image](https://user-images.githubusercontent.com/79633934/121917094-f53d7e80-cd5e-11eb-9cd6-23bfa5ced8c5.png)

**Comment by mhazm** [comment]
Mungkin yg difoto itu maksudnya artis tapi scanlation kali ya? Soalnya karena ini pakai api jadi cuma bisa pakai yg ada didalam api itu sendiri. Mungkin bisa liat disini : [nana-api](https://www.npmjs.com/package/nana-api)
Untuk cmd search pakai bahasa lain itu contohnya
```
k.nh-search keyword jp
k.nh-tag blackmail jp
```
Itu nanti outputnya bakal ngeluarin hasil search di bahasa jepang. Kalau mau bahasa china tinggal ganti jp jadi ch

Kalau memang dari nana-api nggabisa search berdasarkan artist berarti memang gabisa.. Coba diulik lagi di link npm package diatas..

**Comment by rizukurizu** [comment]
baik terimakasih banyak infonya kang, jadi sekali lagi mohon bantuannya ya untuk no 2 dan 3
